Repository yanolja-finalproject/LETS_FE, pull requests merged in 2024-01, with the labels that each got.

#4 Feat: 로그인 페이지 레이아웃 추가
  .eslintrc.json
  public/fonts/Pretendard-Light.woff
  public/fonts/Pretendard-Regular.woff
  public/icons/allCheckIcon.svg
  public/icons/checkIcon.svg
  public/icons/exitButtonIcon.svg
  public/icons/kakaoLogo.svg
  public/icons/leftArrowIcon.svg
  public/icons/mainLogo.svg
  public/icons/mainTitle.svg
  public/icons/naverLogo.svg
  public/next.svg
  public/vercel.svg
  src/app/email-signin/_component/EmailSigninForm.tsx
  src/app/email-signin/_component/TermsForm.tsx
  src/app/email-signin/layout.tsx
  src/app/email-signin/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/signin/_component/SigninForm.tsx
  src/app/signin/_component/SigninHeader.tsx
  src/app/signin/page.tsx
  tailwind.config.ts
Labels: 💡feat

#5 Feat: input, header, button 주요 컴포넌트 분리
  .eslintrc.json
  src/app/_component/Button.tsx
  src/app/_component/DefaultHeader.tsx
  src/app/email-signin/_component/EmailSigninForm.tsx
  src/app/email-signin/_component/SigninInput.tsx
  src/app/email-signin/_component/TermsForm.tsx
  src/app/email-signin/page.tsx
  src/app/email-signup/page.tsx
  src/app/signin/_component/SigninHeader.tsx
Labels: ⚒️refactoring, 💡feat

#6 Feat: 검색페이지 아이템 추가
  public/assets/mainLogo.svg
  public/assets/mainTitle.svg
  public/icons/optionsIcon.svg
  src/app/search-filter/page.tsx
  src/app/search/_component/ContentsBox.tsx
  src/app/search/_component/ForwardBox.tsx
  src/app/search/page.tsx
  tailwind.config.ts
Labels: 💡feat

#7 Feat: 이메일 회원가입 Step1 레이아웃 추가
  public/icons/infoIcon.svg
  public/icons/warningIcon.svg
  src/app/_component/DefaultHeader.tsx
  src/app/email-signin/_component/EmailSigninForm.tsx
  src/app/email-signin/_component/SigninInput.tsx
  src/app/email-signin/_component/SignupErrorText.tsx
  src/app/email-signin/layout.tsx
  src/app/email-signup/_component/SignupEmailInfo.tsx
  src/app/email-signup/_component/SignupEmailWarning.tsx
  src/app/email-signup/_component/SignupStepOne.tsx
  src/app/email-signup/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/signin/page.tsx
  tailwind.config.ts
Labels: 💡feat

#10 Feat: 검색 헤더 생성
  public/icons/searchIcon.svg
  src/app/search/_component/SearchHeader.tsx
  src/app/search/page.tsx
  src/mocks/handlers.ts
  tailwind.config.ts
Labels: 💡feat

#12 Feat: 공통 탭 컴포넌트 생성 및 마이페이지 퍼블리싱
  src/app/_component/common/TabButtons.tsx
  src/app/_component/common/Tabs.tsx
  src/app/_component/common/TabsContainer.tsx
  src/app/my/_component/MyReviewTabContent.tsx
  src/app/my/_component/ReservationTabContent.tsx
  src/app/my/_component/TabTest.tsx
  src/app/my/_component/UpcomingPackages.tsx
  src/app/my/_component/UserInfo.tsx
  src/app/my/_test/Mypage.test.tsx
  src/app/my/page.tsx
  src/utils/renderStars.tsx
Labels: 💡feat

#11 Feat: 결제페이지 초안 퍼블리싱
  src/app/_component/common/BottomNav.tsx
  src/app/payment/_component/.gitkeep
  src/app/payment/_test/.gitkeep
  src/app/payment/page.tsx
  tailwind.config.ts
Labels: 💡feat

#13 Feat: 하단 네비바 생성
  public/icons/navHeartActiveIcon.svg
  public/icons/navHeartIcon.svg
  public/icons/navHomeIcon.svg
  public/icons/navMyIcon.svg
  public/icons/navSearchActiveIcon.svg
  public/icons/navSearchIcon.svg
  src/app/(navbar)/layout.tsx
  src/app/(navbar)/search/_component/ContentsBox.tsx
  src/app/(navbar)/search/_component/ForwardBox.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/app/(navbar)/search/page.tsx
  src/app/(non-navbar)/layout.tsx
  src/app/_component/common/BottomNav.tsx
  src/app/_component/common/atom/Button.tsx
  src/app/_component/common/atom/IconButton.tsx
  src/app/_component/common/atom/TabButtons.tsx
  src/app/_component/common/atom/Tabs.tsx
  src/app/_component/common/layout/BottomNav.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
  src/app/_component/common/layout/TabsContainer.tsx
  src/app/email-signin/_component/EmailSigninForm.tsx
  src/app/email-signin/_component/SigninInput.tsx
  src/app/email-signin/page.tsx
  src/app/email-signup/_component/SignupStepOne.tsx
  src/app/email-signup/_component/SignupStepTwo.tsx
  src/app/email-signup/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/my/_component/MyReviewTabContent.tsx
  src/app/my/_component/ReservationTabContent.tsx
  src/app/my/_component/TabTest.tsx
  src/app/my/_component/UpcomingPackages.tsx
  src/app/my/page.tsx
  src/app/page.tsx
  tailwind.config.ts
Labels: 💡feat

#15 Design: 로그인 페이지 css스타일 수정
  src/app/(non-navbar)/email-signin/_component/AllselectCheckbox.tsx
  src/app/(non-navbar)/email-signin/_component/Checkbox.tsx
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
  src/app/(non-navbar)/email-signin/_component/SignupErrorText.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/app/(non-navbar)/email-signin/_component/layout.tsx
  src/app/(non-navbar)/email-signin/layout.tsx
  src/app/(non-navbar)/email-signin/page.tsx
  src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
  src/app/(non-navbar)/email-signup/_component/SignupEmailInfo.tsx
  src/app/(non-navbar)/email-signup/_component/SignupEmailWarning.tsx
  src/app/(non-navbar)/email-signup/_component/SignupStepOne.tsx
  src/app/(non-navbar)/email-signup/_component/SignupStepTwo.tsx
  src/app/(non-navbar)/email-signup/page.tsx
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
  src/app/(non-navbar)/signin/page.tsx
  src/app/_component/common/atom/Button.tsx
  src/app/email-signin/_component/TermsForm.tsx
  src/app/globals.css
  src/app/signin/_test/Signin.test.tsx
  src/app/signin/page.tsx
Labels: 💡feat

#17 Feat: 로그인, 회원가입 MSW API 추가 및 테스트 액션 추가
  src/api/signin/postSignin.ts
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/mocks/handlers.ts
Labels: 💡feat

#14 Feat: 해시태그 레이아웃 생성
  src/api/search/getHashtags.ts
  src/app/(navbar)/search-filter/page.tsx
  src/app/(navbar)/search/_component/ContentsBox.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/app/(navbar)/search/page.tsx
  src/app/_component/common/atom/Hashtag.tsx
  src/app/_component/common/layout/HashtagsBox.tsx
  src/app/types.ts
  src/utils/hashtagStyle.ts
Labels: 💡feat

#16 Feat: 마이페이지 메뉴/공지/질문 UI
  public/assets/withdraw.png
  public/assets/withdrawLogo.svg
  public/icons/rightArrowIcon.svg
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/_component/TabTest.tsx
  src/app/(navbar)/my/_component/UpcomingPackages.tsx
  src/app/(navbar)/my/_component/UserInfo.tsx
  src/app/(navbar)/my/_types/my.types.ts
  src/app/(navbar)/my/menu/_component/AuthItems.tsx
  src/app/(navbar)/my/menu/_component/ConfirmModal.tsx
  src/app/(navbar)/my/menu/_component/List.tsx
  src/app/(navbar)/my/menu/_component/ListItem.tsx
  src/app/(navbar)/my/menu/_component/MenuSection.tsx
  src/app/(navbar)/my/menu/_component/Withdraw.tsx
  src/app/(navbar)/my/menu/faq/page.tsx
  src/app/(navbar)/my/menu/notice/page.tsx
  src/app/(navbar)/my/menu/page.tsx
  src/app/(navbar)/my/menu/privacy/page.tsx
  src/app/(navbar)/my/menu/terms/page.tsx
  src/app/(navbar)/my/page.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
  src/app/my/_test/Mypage.test.tsx
Labels: 💡feat

#21 Feat: 이메일 로그인 추가
  src/api/signin/postSignin.ts
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
  src/utils/validateEmail.ts
Labels: 💡feat

#19 Design: 메인페이지 레이아웃
  next.config.js
  src/api/home/getAdvertisements.ts
  src/api/home/getPackages.ts
  src/app/(navbar)/home/_component/HomeAdvertisements.tsx
  src/app/(navbar)/home/_component/HomeHashtags.tsx
  src/app/(navbar)/home/_component/HomePackages.tsx
  src/app/(navbar)/home/_component/HomeProsAndCons.tsx
  src/app/(navbar)/home/_component/HomeThemePackage.tsx
  src/app/page.tsx
  src/mocks/handlers.ts
Labels: ⚒️refactoring, 💡feat

#22 Refact: 결제페이지 두번째 리팩토링
  src/app/(navbar)/payment/_component/ProgressBar.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/payment/_component/TopStatus.tsx
  src/app/(navbar)/payment/_test/.gitkeep
  src/app/(navbar)/payment/page.tsx
  src/app/payment/_test/.gitkeep
Labels: ⚒️refactoring

#23 Refactor: 메인 페이지 컴포넌트 폴더 구조 변경
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomePackages.tsx
  src/app/_component/home/HomeProsAndCons.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/page.tsx
Labels: ⚒️refactoring

#26 Feat: 빈화면 레이아웃 추가
  public/assets/sadMainLogo.svg
  src/app/(navbar)/search-result/_component/SearchEmpty.tsx
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/page.tsx
  src/app/_component/common/layout/ContentsBox.tsx
  src/app/_component/common/layout/EmptyBox.tsx
  tailwind.config.ts
Labels: ⚒️refactoring, 💡feat

#25 Feat: 이메일 인증 카운트 추가
  src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
  src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
  src/app/constants.ts
  src/store/useSignupInfoStore.ts
  src/store/useSignupStateStore.ts
Labels: 💡feat

#30 Feat: 체크박스 커스텀 및 로직 추가
  .eslintrc.json
  public/icons/allCheckedIcon.svg
  public/icons/checkedIcon.svg
  src/app/(non-navbar)/email-signin/_component/AllselectCheckbox.tsx
  src/app/(non-navbar)/email-signin/_component/Checkbox.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/store/useCheckStateStore.ts
Labels: 💡feat

#29 Refact: 결제페이지 / Feat: 예약완료페이지 컴포넌트 분리
  src/app/(navbar)/payment/_component/ReservationDone.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/payment/_component/TopStatus.tsx
  src/app/(navbar)/payment/page.tsx
Labels: ⚒️refactoring, 💡feat

#31 Design: 테일윈드 설정 적용
  src/app/(non-navbar)/email-signin/_component/AllselectCheckbox.tsx
  src/app/(non-navbar)/email-signin/_component/Checkbox.tsx
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/app/(non-navbar)/email-signin/_component/layout.tsx
  src/app/(non-navbar)/email-signin/layout.tsx
  src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
  src/app/(non-navbar)/email-signup/_component/SignupEmailInfo.tsx
  src/app/(non-navbar)/email-signup/_component/SignupEmailWarning.tsx
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
  src/app/_component/common/atom/Button.tsx
Labels: ⚒️refactoring

#33 Feat: 기획변경에 따른 추천 검색어 노출
  src/app/(navbar)/search-result/_component/SearchEmpty.tsx
  src/app/(navbar)/search/_component/ForwardContainer.tsx
  src/app/(navbar)/search/_component/Hashtag.tsx
  src/app/(navbar)/search/_component/HashtagsList.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/app/(navbar)/search/page.tsx
  src/app/_component/common/atom/Hashtag.tsx
  src/app/_component/common/atom/IconButton.tsx
  src/app/_component/common/layout/BottomNav.tsx
  src/app/_component/common/layout/EmptyContainer.tsx
  src/app/_component/common/layout/HashtagsContainer.tsx
  src/app/constants.ts
  src/app/types.ts
  src/mocks/handlers.ts
  tailwind.config.ts
Labels: ⚒️refactoring, 💡feat

#34 Refactor: 기본 헤더에 뒤로가기 추가
  src/app/_component/common/layout/DefaultHeader.tsx
Labels: ⚒️refactoring

#32 Refactor: 이메일 회원가입 접근 제한
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
  src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
  src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
  src/app/(non-navbar)/email-signup/page.tsx
Labels: ⚒️refactoring

#36 Feat: 메인페이지 광고구좌 수정
  package-lock.json
  package.json
  src/api/home/getAdvertisements.ts
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/page.tsx
  src/mocks/handlers.ts
Labels: ⚒️refactoring, 💡feat

#37 Feat: 일정 선택 연도, 월 선택 추가
  .eslintrc.json
  public/icons/pageLeftIcon.svg
  public/icons/pageLeftIconLight.svg
  public/icons/pageRightIcon.svg
  public/icons/pageRightIconLight.svg
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderMonth.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/app/(non-navbar)/schedule/[id]/page.tsx
  src/app/layout.tsx
Labels: 💡feat

#38 Feat: 확정 디자인 반영 UI
  public/assets/noItemImg.png
  public/assets/noItemImg.svg
  public/icons/deleteIcon.svg
  public/icons/dotMenuIcon.svg
  public/icons/editIcon.svg
  public/icons/navMyActiveIcon.svg
  public/icons/starIcon.svg
  public/icons/starIconGray.svg
  public/icons/starIconHalf.svg
  public/icons/starIconMini.svg
  src/app/(navbar)/my/_component/Chip.tsx
  src/app/(navbar)/my/_component/InnerSection.tsx
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/_component/UpcomingPackages.tsx
  src/app/(navbar)/my/_component/UserInfo.tsx
  src/app/(navbar)/my/menu/_component/ListItem.tsx
  src/app/(navbar)/my/menu/_component/MenuSection.tsx
  src/app/(navbar)/my/menu/_component/TermsTemplate.tsx
  src/app/(navbar)/my/menu/faq/page.tsx
  src/app/(navbar)/my/menu/notice/page.tsx
  src/app/(navbar)/my/menu/page.tsx
  src/app/(navbar)/my/menu/privacy/page.tsx
  src/app/(navbar)/my/menu/reservation/page.tsx
  src/app/(navbar)/my/menu/terms/page.tsx
  src/app/(navbar)/my/page.tsx
  tailwind.config.ts
Labels: 💡feat

#40 Docs: 리드미 업데이트
  README.md
Labels: 📄docs

#41 Feat: 일정 선택 날짜 선택 기능 및 기본 디자인 추가
  public/icons/pageRightIconLight.svg
  src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderMonth.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/utils/generateDays.ts
  src/utils/getMonthInDate.ts
Labels: 💡feat

#39 Feat: 리뷰 작성 페이지 별점 계산 및 렌더링 구현
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/review/_components/RangeSlider.css
  src/app/(navbar)/my/review/_components/RangeSlider.tsx
  src/app/(navbar)/my/review/_components/ReviewScore.tsx
  src/app/(navbar)/my/review/_components/StarScore.tsx
  src/app/(navbar)/my/review/_components/WriteReview.tsx
  src/app/(navbar)/my/review/page.tsx
  src/utils/renderStars.tsx
Labels: 💡feat

#42 Feat: 날짜별 가격 데이터 표시 추가
  src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
  src/app/(non-navbar)/schedule/[id]/_component/Calender.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/app/(non-navbar)/schedule/[id]/page.tsx
  src/app/types.ts
  src/mocks/data/packageScheduleData.ts
  src/utils/formatDigitNumber.ts
  src/utils/generateDays.ts
Labels: 💡feat

#44 Feat: 캘린더 상품 데이터 MSW연결
  src/api/items/getPackageDetail.ts
  src/api/schedule/getAvailableDates.ts
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderHeader.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderWeeks.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/app/(non-navbar)/schedule/[id]/page.tsx
  src/app/types.ts
  src/mocks/data/packageScheduleData.ts
  src/mocks/handlers.ts
  src/store/useScheduleDateStore.ts
Labels: 💡feat

#43 Feat: 예약완료 페이지
  public/icons/checkIcon3.svg
  src/app/(navbar)/payment/_component/BottomMyPageMenu.tsx
  src/app/(navbar)/payment/_component/ReservationDone.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/payment/_component/Step.tsx
  tailwind.config.ts
Labels: 💡feat

#45 Feat: 선택 상품 이미지 노출, 리액트 쿼리 파일 분리
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/hooks/query/usePackageDetailQuery.ts
  src/hooks/query/useScheduleListQuery.ts
Labels: 💡feat

#46 Feature: 메인 페이지 레이아웃 수정 / 해시태그 버튼 디자인 수정
  src/app/_component/common/layout/DefaultHeader.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/page.tsx
Labels: ⚒️refactoring, 💡feat

#47 Feat: 하단 네비게이션 스크롤 이벤트 추가 (수정)
  public/icons/navHomeActiveIcon.svg
  src/app/_component/common/atom/NavIconButton.tsx
  src/app/_component/common/layout/BottomNav.tsx
  src/hooks/useScrollUp.ts
  src/store/useScrollStore.ts
  tailwind.config.ts
Labels: ⚒️refactoring, 💡feat

#49 Feat: 상세페이지 이미지 캐러셀 추가, 데이터 MSW연결
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMoreButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/DettailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/SwiperBadge.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/hooks/query/usePackageDetailQuery.ts
  src/mocks/data/packageScheduleData.ts
Labels: 💡feat

#50 Feat: 패키지 상세 가격 표시 레이아웃, 컴포넌트 분리
  public/icons/airplaneIcon.svg
  public/icons/bagIcon.svg
  public/icons/calenderIcon.svg
  public/icons/coinIcon.svg
  src/app/(non-navbar)/items/[id]/_component/BadgeList.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/DettailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageInfo.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageTagBadge.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/_component/common/atom/CenterContainer.tsx
Labels: 💡feat

#53 Feat: 상세 페이지 타이포그래피 컴포넌트 글자 웹 크기 추가, 레이아웃 추가
  src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMoreButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/TravelDate.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/(non-navbar)/items/page.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/utils/ReplaceHyphenWithDot.ts
  tailwind.config.ts
Labels: 💡feat

#52 Feat: 마이페이지 첫 화면 msw 데이터 연동
  src/api/my/getMyInfo.ts
  src/api/my/getMyOrders.ts
  src/api/my/getMyReviews.ts
  src/api/my/getMyUpcomingPackage.ts
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/_component/UpcomingPackages.tsx
  src/app/(navbar)/my/_component/UserInfo.tsx
  src/app/constants.ts
  src/app/types.ts
  src/hooks/query/useMyInfoQuery.tsx
  src/hooks/query/useMyOrdersQuery.tsx
  src/hooks/query/useMyReviewsQuery.tsx
  src/hooks/query/useMyUpcomingPackageQuery.tsx
  src/mocks/handlers.ts
Labels: 💡feat

#55 배포
  public/icons/airplaneIcon.svg
  public/icons/bagIcon.svg
  public/icons/calenderIcon.svg
  public/icons/coinIcon.svg
  public/icons/navHomeActiveIcon.svg
  src/api/my/getMyInfo.ts
  src/api/my/getMyOrders.ts
  src/api/my/getMyReviews.ts
  src/api/my/getMyUpcomingPackage.ts
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/_component/UpcomingPackages.tsx
  src/app/(navbar)/my/_component/UserInfo.tsx
  src/app/(non-navbar)/items/[id]/_component/BadgeList.tsx
  src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMoreButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageInfo.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageTagBadge.tsx
  src/app/(non-navbar)/items/[id]/_component/SwiperBadge.tsx
  src/app/(non-navbar)/items/[id]/_component/TravelDate.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/(non-navbar)/items/page.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
  src/app/_component/common/atom/CenterContainer.tsx
  src/app/_component/common/atom/NavIconButton.tsx
  src/app/_component/common/layout/BottomNav.tsx
  src/app/constants.ts
  src/app/types.ts
  src/hooks/query/useMyInfoQuery.tsx
  src/hooks/query/useMyOrdersQuery.tsx
  src/hooks/query/useMyReviewsQuery.tsx
  src/hooks/query/useMyUpcomingPackageQuery.tsx
  src/hooks/query/usePackageDetailQuery.ts
  src/hooks/useScrollUp.ts
  src/mocks/data/packageScheduleData.ts
  src/mocks/handlers.ts
  src/store/useScrollStore.ts
  src/utils/ReplaceHyphenWithDot.ts
  tailwind.config.ts
Labels: 🪄deploy

#54 Feat: 상품 소개 레이아웃 추가
  src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/InclusionExclusionContainer.tsx
  src/app/(non-navbar)/items/[id]/_component/Introduction.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageInfo.tsx
  src/app/(non-navbar)/items/[id]/_component/PriceDetail.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
  src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
  src/app/(non-navbar)/items/[id]/_component/TravelDate.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/(non-navbar)/items/page.tsx
  src/app/(non-navbar)/schedule/[id]/page.tsx
  src/app/_component/common/atom/CenterContainer.tsx
  src/app/_component/common/atom/ColorContainer.tsx
  src/mocks/data/packageScheduleData.ts
Labels: 💡feat

#58 Feat: 상세 페이지 일정표 레이아웃 추가, 탭 컴포넌트 스티키 속성 추가
  public/icons/cupIcon.svg
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
  src/app/_component/common/atom/ColorContainer.tsx
  src/app/_component/common/atom/Tab.tsx
  src/app/_component/common/layout/TabsContainer.tsx
Labels: 💡feat

#59 Feat: 결제페이지 프론트기능구현끝
  src/app/(navbar)/payment/_component/ReservationDone.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/payment/_component/TopStatus.tsx
Labels: 🔧fix, 💡feat

#60 Feat: 공지사항/자주 묻는 질문 목록 조회 msw 연동
  src/api/my/getFaqList.ts
  src/api/my/getNoticeList.ts
  src/app/(navbar)/my/_component/Chip.tsx
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/app/(navbar)/my/_component/NoItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/menu/_component/AuthItems.tsx
  src/app/(navbar)/my/menu/_component/DataList.tsx
  src/app/(navbar)/my/menu/_component/DataListItem.tsx
  src/app/(navbar)/my/menu/_component/List.tsx
  src/app/(navbar)/my/menu/_component/ListItem.tsx
  src/app/(navbar)/my/menu/_component/MenuList.tsx
  src/app/(navbar)/my/menu/_component/MenuListItem.tsx
  src/app/(navbar)/my/menu/faq/page.tsx
  src/app/(navbar)/my/menu/notice/page.tsx
  src/app/(navbar)/my/menu/page.tsx
  src/app/types.ts
  src/hooks/query/useFaqListQuery.tsx
  src/hooks/query/useNoticeListQuery.tsx
  src/mocks/handlers.ts
Labels: ⚒️refactoring, 💡feat

#61 Feat: 100_메인페이지 퍼블리싱
  src/api/home/getPolls.ts
  src/api/home/getThemePackages.ts
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomePackages.tsx
  src/app/_component/home/HomeProsAndCons.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/constants.ts
  src/app/page.tsx
  src/hooks/query/useHomePackageQuery.tsx
  src/mocks/handlers.ts
Labels: ⚒️refactoring, 💡feat

#62 Feat: 상세 페이지 리뷰 데이터 연동 및 무한 스크롤 추가
  src/api/items/getPackageReviews.ts
  src/api/items/getPackageScore.ts
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ReviewItem.tsx
  src/app/(non-navbar)/items/[id]/_component/ReviewRange.tsx
  src/app/(non-navbar)/items/[id]/_component/ReviewRangeList.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
  src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/types.ts
  src/hooks/query/usePackageReveiwQuery.tsx
  src/hooks/query/usePackageScoreQuery.tsx
  src/mocks/data/packageScheduleData.ts
  src/mocks/handlers.ts
  tailwind.config.ts
Labels: 💡feat

#63 Feat: 리뷰 삭제 기능 구현
  src/api/my/deleteMyReview.ts
  src/app/(navbar)/my/_component/MyReviewTabContent.tsx
  src/hooks/query/useDeleteReviewMutation.ts
  src/mocks/data/myReviewData.ts
  src/mocks/handlers.ts
Labels: 💡feat

#69 Feat: 리뷰 없을 때 화면 추가
  src/app/(non-navbar)/items/[id]/_component/NoReviews.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
Labels: 💡feat

#70 Fix: api 요청에 credentials 추가 및 try-catch문으로 변경
  src/api/my/deleteMyReview.ts
  src/api/my/getFaqList.ts
  src/api/my/getMyInfo.ts
  src/api/my/getMyOrders.ts
  src/api/my/getMyReviews.ts
  src/api/my/getMyUpcomingPackage.ts
  src/api/my/getNoticeList.ts
Labels: 🔧fix, ⚒️refactoring

#71 Feat: 상세 페이지 오류 수정, 결제 정보 저장
  src/api/items/getPackageDetail.ts
  src/app/(non-navbar)/items/[id]/_component/ChangeDateButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/StorePerson.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/(non-navbar)/schedule/[id]/page.tsx
  src/hooks/query/usePackageDetailQuery.ts
  src/store/usePaymentStore.ts
Labels: 💡feat

#72 Feat: 상세 페이지 로그인 유저 구분, 탭 컴포넌트 스크롤 속성 추가
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/NoReviews.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
  src/app/_component/common/layout/Dialog.tsx
  src/app/_component/common/layout/TabsContainer.tsx
Labels: 💡feat

#74 Feat: 스케줄 선택 페이지 404페이지 추가
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/(non-navbar)/schedule/[id]/_component/Days.tsx
  src/app/(non-navbar)/schedule/[id]/_component/NotFoundForSchedule.tsx
  src/app/(non-navbar)/schedule/[id]/_component/SelectedProduct.tsx
Labels: 💡feat

#73 Feat: 로그인 페이지 이메일 인증 수정, 소셜 로그인 api함수 추가
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/app/(non-navbar)/email-signin/_component/CertificationCount.tsx
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
Labels: 🔧fix, 💡feat

#77 Feat: 찬반 페이지 레이아웃 및 api함수 추가
  public/icons/selectA.svg
  public/icons/selectAd.svg
  public/icons/selectB.svg
  public/icons/selectBd.svg
  public/icons/vsIcon.svg
  public/icons/vssIcon.svg
  public/icons/vsvIcon.svg
  src/api/balance/getPolls.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/app/(non-navbar)/balance/_component/SelectA.tsx
  src/app/(non-navbar)/balance/_component/SelectAIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectAdIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectB.tsx
  src/app/(non-navbar)/balance/_component/SelectBIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectBdIcon.tsx
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/(non-navbar)/balance/page.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/types.ts
  src/hooks/query/useGetPollsQuery.ts
  src/hooks/query/useGetPollsResult.ts
  src/hooks/query/useSelectPollsMutation.ts
  src/hooks/useOnClickOutside.tsx
  src/mocks/handlers.ts
  tailwind.config.ts
Labels: 💡feat

#78 배포
  public/icons/selectA.svg
  public/icons/selectAd.svg
  public/icons/selectB.svg
  public/icons/selectBd.svg
  public/icons/vsIcon.svg
  public/icons/vssIcon.svg
  public/icons/vsvIcon.svg
  src/api/balance/getPolls.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/app/(non-navbar)/balance/_component/SelectA.tsx
  src/app/(non-navbar)/balance/_component/SelectAIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectAdIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectB.tsx
  src/app/(non-navbar)/balance/_component/SelectBIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectBdIcon.tsx
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/(non-navbar)/balance/page.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/types.ts
  src/hooks/query/useGetPollsQuery.ts
  src/hooks/query/useGetPollsResult.ts
  src/hooks/query/useSelectPollsMutation.ts
  src/hooks/useOnClickOutside.tsx
  src/mocks/handlers.ts
  tailwind.config.ts
Labels: 🪄deploy

#79 Feat: 필터 검색 페이지 기능구현 완료
  src/api/search/getHashtags.ts
  src/api/search/getSearchCount.ts
  src/app/(navbar)/my/review/_components/RangeSlider.tsx
  src/app/(navbar)/search-filter/_component/Concept.tsx
  src/app/(navbar)/search-filter/_component/Destination.tsx
  src/app/(navbar)/search-filter/_component/DestinationsList.tsx
  src/app/(navbar)/search-filter/_component/PriceRangeBar.tsx
  src/app/(navbar)/search-filter/_component/SearchButton.tsx
  src/app/(navbar)/search-filter/_hooks/useSearchCount.ts
  src/app/(navbar)/search-filter/page.tsx
  src/app/(navbar)/search-result/page.tsx
  src/app/_component/common/layout/ContentsContainer.tsx
  src/app/_component/common/layout/EmptyContainer.tsx
  src/hooks/query/useSearchCountQuery.ts
  src/mocks/handlers.ts
  src/store/useSearchFilterStore.ts
Labels: ⚒️refactoring, 💡feat

#80 Fix: 로그인 api수정 및 타입 수정
  src/api/balance/getPolls.ts
  src/api/signin/getEmailAuth.ts
  src/api/signin/postCertification.ts
  src/api/signin/postSignin.ts
  src/api/signin/postSignup.ts
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/page.tsx
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
  src/hooks/query/useGetPollsQuery.ts
Labels: 💡feat

#82 Env: 로컬 환경 커스텀 https서버 추가
  package.json
  server.js
Labels: 💡feat

#84 Refactor: api요청 함수 수정
  src/api/balance/getPolls.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/api/items/getPackageDetail.ts
  src/api/items/getPackageReviews.ts
  src/api/items/getPackageScore.ts
  src/api/schedule/getAvailableDates.ts
  src/api/schedule/getPackageSchedules.ts
  src/api/signin/getEmailAuth.ts
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/api/signin/postCertification.ts
  src/api/signin/postSignin.ts
  src/api/signin/postSignup.ts
Labels: ⚒️refactoring

#85 Refactor: 상세 페이지 prefetch 오류 수정
  .eslintrc.json
  src/app/(non-navbar)/items/[id]/_component/Introduction.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
Labels: ⚒️refactoring

#86 배포
  .eslintrc.json
  next.config.js
  package.json
  server.js
  src/api/balance/getPolls.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/api/home/getHi.ts
  src/api/home/getPackages.ts
  src/api/items/getPackageDetail.ts
  src/api/items/getPackageReviews.ts
  src/api/items/getPackageScore.ts
  src/api/schedule/getAvailableDates.ts
  src/api/schedule/getPackageSchedules.ts
  src/api/signin/getEmailAuth.ts
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/api/signin/postCertification.ts
  src/api/signin/postSignin.ts
  src/api/signin/postSignup.ts
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/search/_component/Hashtag.tsx
  src/app/(navbar)/search/_component/Keyword.tsx
  src/app/(navbar)/search/_component/KeywordsList.tsx
  src/app/(navbar)/search/_component/Package.tsx
  src/app/(navbar)/search/_component/PackagesList.tsx
  src/app/(navbar)/search/page.tsx
  src/app/(non-navbar)/items/[id]/_component/Introduction.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/_component/common/atom/LikeButton.tsx
  src/app/_component/home/HomePackages.tsx
  src/app/types.ts
  src/hooks/query/useHomePackageQuery.tsx
  src/hooks/query/usePackageListQuery.tsx
  src/mocks/handlers.ts
Labels: 🪄deploy

#88 Feat: 공지사항/자주 묻는 질문 상세보기 페이지 구현
  src/api/my/getFaqDetail.ts
  src/api/my/getNoticeDetail.ts
  src/app/(navbar)/my/_component/Chip.tsx
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/UpcomingPackages.tsx
  src/app/(navbar)/my/_component/UserInfo.tsx
  src/app/(navbar)/my/menu/_component/DataList.tsx
  src/app/(navbar)/my/menu/_component/DataListItem.tsx
  src/app/(navbar)/my/menu/faq/[id]/page.tsx
  src/app/(navbar)/my/menu/notice/[id]/page.tsx
  src/app/(navbar)/my/page.tsx
  src/app/(navbar)/my/review/page.tsx
  src/app/constants.ts
  src/hooks/query/useFaqDetailQuery.ts
  src/hooks/query/useNoticeDetailQuery.ts
  src/mocks/handlers.ts
Labels: 💡feat

#87 Feat: 비교페이지+찜 페이지 구현 및 수정
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/ProductSummary.tsx
  src/app/(navbar)/compare/_component/WishListInfo.tsx
  src/app/(navbar)/compare/_component/WishListNone.tsx
  src/app/(navbar)/compare/_component/WishListPage.tsx
  src/app/(navbar)/compare/page.tsx
Labels: 🔧fix, ⚒️refactoring, 💡feat

#90 Refactor: 상세 페이지 리팩토링
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailTypography.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/_component/StorePerson.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
Labels: ⚒️refactoring, 💡feat

#93 Fix: 상세 페이지 예약 모달 최상단 적용 안되는 오류 해결
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
Labels: 🔧fix, 💡feat

#92 Refactor: 로그인, 회원가입 에러 메시지 수정, redirect url 추가
  src/app/(non-navbar)/email-signin/_component/EmailSigninForm.tsx
  src/app/(non-navbar)/email-signin/_component/SigninInput.tsx
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
  src/app/(non-navbar)/email-signup/_component/EmailAuth.tsx
  src/app/(non-navbar)/email-signup/_component/EnterPassword.tsx
  src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
  src/app/(non-navbar)/signin/page.tsx
  src/app/_component/common/layout/Dialog.tsx
  src/hooks/query/useGetEmailAuthQuery.ts
  src/hooks/query/usePostCertificationMutation.ts
  src/hooks/query/usePostSigninMutation.ts
  src/hooks/query/usePostSignupMutation.ts
Labels: 🔧fix, ⚒️refactoring, 💡feat

#94 Refactor: 상세 페이지 스크롤 버튼 애니메이션 수정
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
  tailwind.config.ts
Labels: ⚒️refactoring

#91 FIx: 코드수정
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MoreButton.tsx
  src/app/(navbar)/compare/_component/Schedule.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
Labels: 🔧fix

#97 Feat: 검색 결과페이지 api 연결
  src/api/search/getHashtagSearchResult.ts
  src/api/search/getKeywordSearchResult.ts
  src/app/(navbar)/search-filter/_component/SearchButton.tsx
  src/app/(navbar)/search-filter/_hooks/useSearchCount.ts
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/Options.tsx
  src/app/(navbar)/search-result/_component/Package.tsx
  src/app/(navbar)/search-result/_component/PackagesList.tsx
  src/app/(navbar)/search-result/_component/SearchEmpty.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
  src/app/(navbar)/search-result/_hooks/useKeywordResult.ts
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/_component/Keyword.tsx
  src/app/(navbar)/search/_component/Package.tsx
  src/app/(navbar)/search/_component/PackagesList.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/app/types.ts
  src/hooks/query/useHashtagSearchQuery.ts
  src/hooks/query/useKeywordSearchQuery.ts
  src/mocks/handlers.ts
Labels: 💡feat

#96 Feat: 200_광고구좌페이지 퍼블리싱
  next.config.js
  src/api/advertisement/getAdvertisementInfo.ts
  src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementInfomation.tsx
  src/app/(non-navbar)/advertisement/[id]/page.tsx
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/page.tsx
  src/app/types.ts
  src/hooks/query/useAdvertisementInfoQuery.ts
  src/mocks/handlers.ts
  src/utils/formatLongText.ts
  src/utils/getAdsHeaderText.ts
Labels: ⚒️refactoring, 💡feat

#98 Fix: 결제 페이지 예약 추가
  src/api/items/postOrder.ts
  src/app/(navbar)/payment/_component/ReservationDone.tsx
  src/app/(navbar)/payment/_component/ReservationInfo.tsx
  src/app/(navbar)/payment/page.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/hooks/query/useOrderMutation.ts
  src/store/usePaymentStore.ts
Labels: 🔧fix, ⚒️refactoring

#99 Feat: 검색 결과 페이지 퍼블리싱
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/Package.tsx
  src/app/(navbar)/search-result/_component/PackagesList.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/_component/Package.tsx
Labels: ⚒️refactoring, 💡feat

#101 Fix: 결제 인원 선택 모달 인원 오류 수정
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
Labels: 🔧fix

#102 배포
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
Labels: 🪄deploy

#104 Fix: 소셜 로그인 api 수정
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 💡feat

#103 Fix: 결제 인원선택 모달 작동 위치 변경
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/_component/common/layout/BottomSlideModal.tsx
Labels: 🔧fix

#105 배포
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
  src/app/_component/common/layout/BottomSlideModal.tsx
Labels: 🪄deploy

#106 Fix: 패키지 상세 정보 api 쿠키 정보 추가
  src/api/items/getPackageDetail.ts
  src/app/(non-navbar)/items/[id]/page.tsx
Labels: 🔧fix

#107 Feat: 좋아요 기능 추가
  src/api/home/deleteWish.ts
  src/api/home/postIsWish.ts
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/InclusionExclusionContainer.tsx
  src/app/_component/common/atom/LikeButton.tsx
  src/hooks/query/useDeleteWishMutation.ts
  src/hooks/query/useIsWishMutation.ts
Labels: 💡feat

#108 Fix: 디테일 페이지 데이터 fetch오류 수정
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/hooks/query/usePackageDetailQuery.ts
Labels: 🔧fix

#110 Fix: 좋아요 존재하지 않는 패키지 핸들링 추가
  src/app/_component/common/atom/LikeButton.tsx
Labels: 💡feat

#111 Feat: 검색 결과페이지에서 선택된 옵션 삭제 기능
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/Options.tsx
  src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
  src/app/(navbar)/search-result/_hooks/useOptions.ts
  src/app/(navbar)/search-result/page.tsx
Labels: 💡feat

#113 Fix: Oauth API credentials 제거
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
Labels: 🔧fix

#114 배포
  package-lock.json
  package.json
  src/api/home/deleteWish.ts
  src/api/home/postIsWish.ts
  src/api/items/getPackageDetail.ts
  src/api/my/getMyInfo.ts
  src/api/my/patchMyInfo.ts
  src/api/my/putMyPassword.ts
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/menu/reservation/page.tsx
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/Options.tsx
  src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
  src/app/(navbar)/search-result/_hooks/useOptions.ts
  src/app/(navbar)/search-result/page.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/InclusionExclusionContainer.tsx
  src/app/(non-navbar)/items/[id]/_component/ScheduleDetail.tsx
  src/app/(non-navbar)/items/[id]/page.tsx
  src/app/(non-navbar)/my/info/_components.tsx/AddressSearch.tsx
  src/app/(non-navbar)/my/info/_components.tsx/InputWithButton.tsx
  src/app/(non-navbar)/my/info/page.tsx
  src/app/(non-navbar)/schedule/[id]/_component/CalenderDays.tsx
  src/app/_component/common/atom/LikeButton.tsx
  src/app/types.ts
  src/hooks/query/useDeleteWishMutation.ts
  src/hooks/query/useIsWishMutation.ts
  src/hooks/query/usePackageDetailQuery.ts
  src/hooks/query/useUpdateMyInfoMutation.ts
  src/hooks/query/useUpdatePasswordMutation.ts
  src/mocks/handlers.ts
  src/utils/formatPhoneNumber.ts
Labels: 🪄deploy

#115 Fix: 소셜 로그인 api수정
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
Labels: 🔧fix, 💡feat

#116 배포
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
Labels: 🪄deploy

#117 Fix: Oauth API 수정
  src/api/signin/getNaverAuth.ts
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🔧fix

#118 배포
  src/api/signin/getNaverAuth.ts
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🪄deploy

#120 배포
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
Labels: 🪄deploy

#121 Fix: Oauth API 수정
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
Labels: 🔧fix

#122 배포
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
Labels: 🪄deploy

#123 Fix: Oauth API 수정
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🔧fix

#124 배포
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🪄deploy

#125 Fix: Oauth API 수정
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🔧fix

#126 배포
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🪄deploy

#127 Fix: Oauth 링크로 요청
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🔧fix

#128 배포
  src/api/signin/getKakaoAuth.ts
  src/api/signin/getNaverAuth.ts
  src/app/(non-navbar)/signin/_component/KakaoLoginButton.tsx
  src/app/(non-navbar)/signin/_component/NaverLoginButton.tsx
Labels: 🪄deploy

#129 Feat: 검색 결과페이지 정렬 추가
  src/app/(navbar)/search-result/_component/DropDownBox.tsx
  src/app/(navbar)/search-result/_component/DropDownOption.tsx
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/constants.ts
Labels: 💡feat

#130 배포
  src/app/(navbar)/search-result/_component/DropDownBox.tsx
  src/app/(navbar)/search-result/_component/DropDownOption.tsx
  src/app/(navbar)/search-result/_component/Option.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/constants.ts
Labels: 🪄deploy

#131 Fix: 검색 페이지 데이터 뎁스 수정
  src/app/(navbar)/search/_component/PackagesList.tsx
Labels: 🐞bug

#132 배포
  src/app/(navbar)/search/_component/PackagesList.tsx
Labels: 🪄deploy

#134 Feat: 찬반 투표 페이지 완성
  src/api/balance/getPolls.ts
  src/api/balance/getPollsMain.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/app/(non-navbar)/balance/_component/SelectA.tsx
  src/app/(non-navbar)/balance/_component/SelectB.tsx
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/(non-navbar)/balance/page.tsx
  src/hooks/query/useGetPollsMainQuery.ts
  src/hooks/query/useGetPollsResult.ts
  src/hooks/query/usePollsQuery.ts
Labels: 💡feat

#136 Refactor: 상세 페이지
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
  src/app/_component/common/layout/BottomSlideModal.tsx
  src/app/_component/common/layout/Dialog.tsx
Labels: 🔧fix, ⚒️refactoring, 💡feat

#137 Design: 에러 페이지 버튼 디자인 수정
  src/app/(navbar)/error.tsx
  src/app/(non-navbar)/error.tsx
Labels: ⚒️refactoring

#138 배포
  src/api/balance/getPolls.ts
  src/api/balance/getPollsMain.ts
  src/api/balance/getPollsResult.ts
  src/api/balance/postPolls.ts
  src/api/my/getMyOrders.ts
  src/app/(navbar)/error.tsx
  src/app/(navbar)/my/_component/ReservationItem.tsx
  src/app/(navbar)/my/_component/ReservationTabContent.tsx
  src/app/(navbar)/my/menu/reservation/page.tsx
  src/app/(navbar)/my/review/page.tsx
  src/app/(non-navbar)/balance/_component/SelectA.tsx
  src/app/(non-navbar)/balance/_component/SelectB.tsx
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/(non-navbar)/balance/page.tsx
  src/app/(non-navbar)/error.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
  src/app/_component/common/layout/BottomSlideModal.tsx
  src/app/_component/common/layout/Dialog.tsx
  src/app/types.ts
  src/hooks/query/useGetPollsMainQuery.ts
  src/hooks/query/useGetPollsResult.ts
  src/hooks/query/useMyOrdersQuery.ts
  src/hooks/query/usePollsQuery.ts
  src/hooks/useInfiniteScroll.ts
  src/hooks/useSortedOrderList.ts
  src/utils/canWriteReview.ts
  src/utils/sortOrderList.ts
Labels: 🪄deploy

#139 Feat: 400_여행테마패키지 페이지 퍼블리싱
  public/assets/bestTheme.png
  src/api/theme/getThemeDetail.ts
  src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementDetail.tsx
  src/app/(non-navbar)/advertisement/[id]/page.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/page.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/constants.ts
  src/app/types.ts
  src/hooks/query/useThemeQuery.ts
Labels: ⚒️refactoring, 💡feat

#141 배포
  public/assets/bestTheme.png
  src/api/theme/getThemeDetail.ts
  src/app/(navbar)/search-filter/_component/Destination.tsx
  src/app/(navbar)/search-filter/_component/DestinationsList.tsx
  src/app/(navbar)/search-filter/_hooks/useSearchCount.ts
  src/app/(navbar)/search-filter/page.tsx
  src/app/(navbar)/search-result/_hooks/useKeywordResult.ts
  src/app/(navbar)/search-result/_hooks/useOptions.ts
  src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementDetail.tsx
  src/app/(non-navbar)/advertisement/[id]/page.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/page.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/constants.ts
  src/app/types.ts
  src/hooks/query/useThemeQuery.ts
Labels: 🪄deploy

#142 Fix: 헤더 이동 url속성 추가
  src/app/(non-navbar)/balance/page.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
  src/hooks/query/usePackageReveiwQuery.tsx
Labels: 🔧fix

#145 Refact: 비교페이지 API바인딩 Test
  public/icons/refreshIcon.svg
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/Schedule.tsx
  src/app/(navbar)/compare/_component/ScheduleItems.ts
  src/app/(navbar)/compare/_component/WishListInfo.tsx
  src/app/(navbar)/compare/page.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
Labels: 🔧fix, ⚒️refactoring

#146 Feat: 찜페이지 기능 구현
  src/api/heart/getWishList.ts
  src/app/(navbar)/heart/_component/Tag.tsx
  src/app/(navbar)/heart/_component/Wish.tsx
  src/app/(navbar)/heart/_component/WishesList.tsx
  src/app/(navbar)/heart/page.tsx
  src/app/_component/common/atom/LikeButton.tsx
  src/hooks/query/useGetWishListQuery.ts
Labels: 💡feat

#147 Refactor: 검색 결과 페이지 완료!
  src/api/search/getHashtagSearchResult.ts
  src/api/search/getKeywordSearchResult.ts
  src/app/(navbar)/search-result/_component/DropDownBox.tsx
  src/app/(navbar)/search-result/_component/Package.tsx
  src/app/(navbar)/search-result/_component/PackagesList.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
  src/app/(navbar)/search-result/_hooks/useKeywordResult.ts
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/_component/PackagesList.tsx
  src/app/types.ts
  src/hooks/query/useHashtagSearchQuery.ts
  src/hooks/query/useKeywordSearchQuery.ts
Labels: ⚒️refactoring, 💡feat

#151 Feat: 리뷰 작성 api요청 연결
  public/test.svg
  public/test2.svg
  public/test3.svg
  src/api/my/postMyReview.ts
  src/app/(navbar)/my/review/_components/ReviewForm.tsx
  src/app/(navbar)/my/review/_components/ReviewScore.tsx
  src/app/(navbar)/my/review/_components/StarScore.tsx
  src/app/(navbar)/my/review/_components/WriteReview.tsx
  src/app/(navbar)/my/review/page.tsx
  src/hooks/query/usePostReviewMutation.ts
Labels: ⚒️refactoring

#143 Feat: 메인 초특가 페이지 데이터 연결 중간 PR
  public/assets/mainPoll.png
  public/assets/mainPollA.png
  public/assets/mainPollB.png
  public/test.svg
  public/test2.svg
  public/test3.svg
  src/api/home/getBestPackages.ts
  src/api/home/getPackages.ts
  src/api/home/getSalePackages.ts
  src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementDetail.tsx
  src/app/(non-navbar)/advertisement/[id]/page.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/theme/[id]/_component/BestThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/page.tsx
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomePackages.tsx
  src/app/_component/home/HomeProsAndCons.tsx
  src/app/_component/home/HomeSalePackages.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/constants.ts
  src/app/page.tsx
  src/hooks/query/useBestThemeQuery.ts
  src/hooks/query/usePackageListQuery.tsx
  src/hooks/query/useThemeQuery.ts
Labels: ⚒️refactoring, 💡feat

#150 Feat: 상품 비교 상품 선택 기능
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/WishListInfo.tsx
  src/app/(navbar)/compare/_component/WishListPage.tsx
  src/app/(navbar)/compare/page.tsx
Labels: ⚒️refactoring

#152 Feat: 찜목록 무한스크롤 구현
  src/api/heart/getWishList.ts
  src/app/(navbar)/heart/_component/Tag.tsx
  src/app/(navbar)/heart/_component/WishesList.tsx
  src/app/(navbar)/heart/page.tsx
  src/app/(navbar)/search-result/_hooks/useHashtagResult.ts
Labels: 💡feat

#153 Refactor: 테마 페이지 패키지 이미지 속성 수정
  src/app/(non-navbar)/theme/[id]/_component/BestThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
  src/hooks/query/usePackageListQuery.tsx
Labels: ⚒️refactoring, 💡feat

#155 Fix: 상세 페이지, 상품 비교 연동 및 수정
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/WishListInfo.tsx
  src/app/(navbar)/compare/_component/WishListPage.tsx
  src/app/(navbar)/compare/page.tsx
  src/app/(non-navbar)/items/[id]/_component/BadgeList.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailBottomButton.tsx
  src/app/(non-navbar)/items/[id]/_component/PackageTagBadge.tsx
  src/app/(non-navbar)/items/[id]/_component/ReviewItem.tsx
  src/app/(non-navbar)/items/[id]/_component/Reviews.tsx
  src/hooks/query/usePackageReveiwQuery.tsx
Labels: ⚒️refactoring

#157 Fix: 찬반 페이지 이벤트 없을때 예외 추가
  src/app/(non-navbar)/balance/_component/ViewOption.tsx
  src/app/(non-navbar)/balance/page.tsx
Labels: 🔧fix, 🪄deploy

#158 Fix: 찬반 페이지 메타데이터 타이틀 수정
  src/app/(non-navbar)/balance/page.tsx
Labels: 🔧fix

#156 Feat: 찜페이지에서 좋아요 해제
  src/api/home/getSalePackages.ts
  src/app/(navbar)/heart/_component/Tag.tsx
  src/app/(navbar)/heart/_component/Wish.tsx
Labels: 💡feat

#161 Fix: 비교페이지 쇼핑센터 방문일정 부분 수정
  next.config.js
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/LeftProgressBar.tsx
  src/app/(navbar)/compare/_component/RightProgressBar.tsx
Labels: 🔧fix

#164 Fix: 비교페이지 쇼핑센터 방문일정 오류 해결
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
Labels: 🔧fix

#165 Refactor: 자잘한 디자인 수정 및 에러 핸들링 추가
  public/assets/imageLoadError.png
  src/api/search/getHashtagSearchResult.ts
  src/api/search/getKeywordSearchResult.ts
  src/app/(navbar)/search-result/_component/Package.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/_component/PackagesList.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
  src/hooks/useImage.ts
  src/utils/hashtagStyle.ts
Labels: 🔧fix, ⚒️refactoring, 💡feat

#167 Fix: 수정
  src/app/(navbar)/compare/_component/LeftProgressBar.tsx
  src/app/(navbar)/compare/_component/RightProgressBar.tsx
Labels: 🔧fix

#169 Fix: 프로그레스바 오류수정2
  src/app/(navbar)/compare/_component/LeftProgressBar.tsx
  src/app/(navbar)/compare/_component/RightProgressBar.tsx
Labels: 🔧fix

#171 Fix: 메인 페이지 기본 ui 개선
  public/icons/balanceMain.png
  public/icons/balanceMainA.svg
  public/icons/balanceMainB.svg
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/_component/home/HomeHashtags.tsx
  src/app/_component/home/HomeProsAndCons.tsx
  src/app/_component/home/HomeSalePackages.tsx
  src/app/_component/home/HomeThemePackage.tsx
  tailwind.config.ts
Labels: 💡feat

#175 feat: 테마페이지 API 변경 대응 개발
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
Labels: ⚒️refactoring

#180 Feat: 이미지 슬라이드 메인 테마 추가
  src/app/(non-navbar)/items/[id]/_component/DetailMain.tsx
  src/app/(non-navbar)/items/[id]/_component/DetailSwiper.tsx
  src/app/(non-navbar)/items/[id]/_component/SwiperBadge.tsx
  src/app/_component/home/HomeAdvertisements.tsx
Labels: 💡feat

#183 Design: 비교 페이지 UI 개선
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/LeftProductSummary.tsx
  src/app/(navbar)/compare/_component/LeftProgressBar.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/RightProductSummary.tsx
  src/app/(navbar)/compare/_component/RightProgressBar.tsx
  src/app/(navbar)/compare/_component/WishListPage.tsx
  src/app/(navbar)/compare/page.tsx
Labels: ⚒️refactoring, 💡feat

#187 Refactor: 이미지 비율 처리 / 테마페이지 로딩스피너 적용
  src/app/(non-navbar)/advertisement/[id]/_component/AdvertisementDetail.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
Labels: ⚒️refactoring

#184 Refactor: 비교 -> 찜
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/WishListInfo.tsx
  src/app/(navbar)/compare/_component/WishListNone.tsx
  src/app/(navbar)/compare/page.tsx
  src/app/(navbar)/heart/_component/Wish.tsx
  src/app/(navbar)/heart/_component/WishesList.tsx
  src/app/(navbar)/heart/page.tsx
  src/app/_component/common/atom/LikeButton.tsx
  src/app/_component/common/atom/Tag.tsx
Labels: 🔧fix, ⚒️refactoring, 💡feat

#188 Feat: 비교 페이지 기능 완성, ui 개선
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/_component/LeftProgressBar.tsx
  src/app/(navbar)/compare/_component/MyPicProduct.tsx
  src/app/(navbar)/compare/_component/RightProgressBar.tsx
  src/app/_component/common/layout/BottomNav.tsx
Labels: 🔧fix, ⚒️refactoring, 💡feat

#190 Refactor: 검색 페이지 자잘한 이슈 해결
  src/app/(navbar)/search-filter/_component/Concept.tsx
  src/app/(navbar)/search-filter/_component/Destination.tsx
  src/app/(navbar)/search-filter/_component/PriceRangeBar.tsx
  src/app/(navbar)/search-result/page.tsx
  src/app/(navbar)/search/_component/SearchHeader.tsx
  src/store/useSearchFilterStore.ts
Labels: 🔧fix, ⚒️refactoring, 💡feat

#192 Feature/theme infinite scroll
  src/api/home/getBestPackages.ts
  src/api/theme/getThemeDetail.ts
  src/app/(non-navbar)/theme/[id]/_component/BestTheme.tsx
  src/app/(non-navbar)/theme/[id]/_component/BestThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/_component/Theme.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemeDetail.tsx
  src/app/(non-navbar)/theme/[id]/_component/ThemePackageItem.tsx
  src/app/(non-navbar)/theme/[id]/_hooks/useBestThemeResult.ts
  src/app/(non-navbar)/theme/[id]/_hooks/useThemeResult.ts
  src/app/(non-navbar)/theme/[id]/page.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/hooks/query/useBestThemeQuery.ts
  src/hooks/query/useThemeQuery.ts
Labels: ⚒️refactoring, 💡feat

#196 Fix: 비교 페이지 조건 추가, 하단 바 스크롤 조건 변경
  src/app/(navbar)/compare/_component/ChangeCompareProduct.tsx
  src/app/(navbar)/compare/page.tsx
  src/app/(non-navbar)/email-signup/_component/SignupComplete.tsx
  src/app/_component/common/atom/NavIconButton.tsx
  src/app/_component/common/layout/BottomNav.tsx
  src/app/_component/common/layout/DefaultHeader.tsx
Labels: 💡feat

#199 Feat: 공지사항 줄바꿈 및 로딩스피너 추가
  src/api/my/getFaqList.ts
  src/app/(navbar)/my/menu/_component/DataListItem.tsx
  src/app/(navbar)/my/menu/faq/[id]/page.tsx
  src/app/(navbar)/my/menu/faq/page.tsx
  src/app/(navbar)/my/menu/notice/[id]/page.tsx
  src/app/(navbar)/my/menu/notice/page.tsx
  src/app/_component/common/layout/SmallSpinner.tsx
  src/app/types.ts
  src/hooks/query/useFaqDetailQuery.ts
  src/hooks/query/useNoticeDetailQuery.ts
Labels: ⚒️refactoring

#200 Refactor: 자잘한 디자인 수정,,
  src/app/(navbar)/heart/_component/Wish.tsx
  src/app/(navbar)/heart/_component/WishesList.tsx
  src/app/(navbar)/heart/page.tsx
  src/app/(navbar)/search-filter/_component/Concept.tsx
  src/app/(navbar)/search-filter/_component/Destination.tsx
  src/app/(navbar)/search-result/_component/Options.tsx
  src/app/(navbar)/search-result/_component/Package.tsx
  src/app/(navbar)/search-result/_component/PackagesList.tsx
  src/app/(navbar)/search-result/_component/SearchResult.tsx
  src/app/(navbar)/search-result/_component/SkeletonItem.tsx
  src/app/(navbar)/search-result/page.tsx
  src/hooks/useDefaultImage.ts
Labels: ⚒️refactoring

#206 Fix: 상세 페이지 인원 선택 오류 수정
  public/icons/minusGrayIcon.svg
  public/icons/plusGrayIcon.svg
  src/app/(non-navbar)/advertisement/[id]/page.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/(non-navbar)/items/[id]/_component/ReviewRange.tsx
  src/app/(non-navbar)/items/[id]/_component/StorePerson.tsx
Labels: 🔧fix

#207 Fix: 하단 바 스크롤 중지 동작 상세 페이지 적용
  src/app/(non-navbar)/items/[id]/_component/ItemDetailBottom.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
Labels: 🔧fix, 💡feat

#208 Fix: 콘솔 제거, 필요없는 파일 제거
  src/app/(non-navbar)/balance/_component/SelectAIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectAdIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectBIcon.tsx
  src/app/(non-navbar)/balance/_component/SelectBdIcon.tsx
  src/app/(non-navbar)/balance/_component/ViewResult.tsx
  src/app/_component/common/atom/ScrollToUpButton.tsx
Labels: 🔧fix, ⚒️refactoring

#209 Refactor / 메인 페이지 성능 개선
  src/app/_component/home/HomeAdvertisements.tsx
  src/app/_component/home/HomeThemePackage.tsx
  src/app/page.tsx
Labels: ⚒️refactoring

#210 Fix: 회원가입 약관 동의 모달 z-index 추가
  src/app/(non-navbar)/email-signin/_component/TermsForm.tsx
Labels: 🔧fix, ⚒️refactoring
